CREATE TABLE USUARIO
 (
 	ID INT NOT NULL,
 	NOME CHARACTER VARYING(80) NOT NULL,
 	EMAIL CHARACTER VARYING(80) NOT NULL,
 	SENHA CHARACTER VARYING (15) NOT NULL,
 	ADMIN BOOLEAN NOT NULL,
 	CONSTRAINT PK_ID PRIMARY KEY (ID)
 );
 
 CREATE TABLE FILME
 (
 	ID INT NOT NULL,
 	NOME CHARACTER VARYING(100) NOT NULL,
 	EPISODIOS INT,
 	GENERO CHARACTER(15),
	PAIS CHARACTER VARYING(15),
	IDIOMA CHARACTER VARYING(15),
	COR BOOLEAN,
	RESUMO CHARACTER VARYING(500),
	CURIOSIDADES CHARACTER VARYING(500),
	CONSTRAINT PK_ID PRIMARY KEY (ID)
 );
 
 CREATE TABLE AVALIACAO
 (
 	USUARIO INT NOT NULL,
 	FILME INT NOT NULL,
 	MEDIA_VOTOS INT,
 	CONSTRAINT PK_USUARIO_FILME PRIMARY KEY (USUARIO, FILME),
 	CONSTRAINT FK_USUARIO FOREIGN KEY (USUARIO) REFERENCES USUARIO(ID),
 	CONSTRAINT FK_FILME_A FOREIGN KEY (FILME) REFERENCES FILME(ID)
 );
 
 CREATE TABLE PESSOA_FILME
 (
 	ID INT NOT NULL,
 	NOME CHARACTER VARYING(80),
 	NASC DATE,
 	BIOGRAFIA CHARACTER VARYING(500),
 	CONSTRAINT PK_ID PRIMARY KEY (ID)
 );
 
 CREATE TABLE PARTICIPACAO
 (
 	PARTICIPANTE INT NOT NULL,
 	FILME INT NOT NULL,
 	FUNCAO CHARACTER VARYING(10),
 	CONSTRAINT PK_PARTICIPANTE_FILME PRIMARY KEY (PARTICIPANTE, FILME),
 	CONSTRAINT FK_PARTICIPANTE FOREIGN KEY (PARTICIPANTE) REFERENCES PESSOA_FILME(ID),
 	CONSTRAINT FK_FILME_p FOREIGN KEY (FILME) REFERENCES FILME(ID)
 );